from fastapi import APIRouter
from config.falai import fal_client
from models.falai_models import TryOnInput
from models.global_models import GeneralResponse
from config.logger import logger

router = APIRouter()


@router.post("/falai/virtual-try-on")
async def try_on(input_data: TryOnInput):
    try:
        logger.info("Starting virtual try-on process...")
        logger.debug(f"Input data received: {input_data}")

        handler = await fal_client.submit_async(
            "fashn/tryon",
            arguments={
                "model_image": input_data.model_image,
                "garment_image": input_data.garment_image,
                "category": input_data.category,
                "garment_photo_type": input_data.garment_photo_type,
                "nsfw_filter": input_data.nsfw_filter,
                "guidance_scale": input_data.guidance_scale,
                "timesteps": input_data.timesteps,
                "seed": input_data.seed,
                "num_samples": input_data.num_samples,
            },
        )

        logger.info("Request submitted to FALAI client.")

        result = await handler.get()
        images = result.get("images", [])

        if not images:
            logger.warning("No images generated by FALAI.")
            return GeneralResponse(
                status_code=204, data=None, message="No images generated."
            )

        logger.info(f"Images generated successfully: {len(images)} images.")
        return GeneralResponse(
            status_code=200,
            data={"images": [image["url"] for image in images]},
            message="Images generated successfully.",
        )

    except Exception as e:
        logger.error(
            f"An error occurred during the try-on process: {str(e)}", exc_info=True
        )
        return GeneralResponse(
            status_code=500, data=None, message=f"An error occurred: {str(e)}"
        )
