FROM tiangolo/uvicorn-gunicorn-fastapi:python3.11-slim

WORKDIR /app

COPY . .


# Install necessary dependencies, including FastAPI and other required packages
RUN pip install --no-cache-dir -r requirements.txt










