name: Detect Changes in watermark_service

on:
  push:
    branches:
      - '**'   # Trigger on all branches
    paths:
      - 'watermark_service/**/*'  # Monitor changes only in watermark_service

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Handle changes in watermark_service
        id: detect-changes
        run: |
          # Get the commit ID
          commit_id=$(git rev-parse HEAD)
          echo "Setting output for last non-merged commit ${commit_id}"

          # Get the files changed in the current commit
          files_changed=$(git diff-tree --no-commit-id --name-only -r ${commit_id} | xargs)

          # Print the list of changed files for debugging
          echo "Changed files: ${files_changed}"

          # Initialize an array to store parent folders related to watermark_service
          parent_folders=()

          # Loop through each changed file and check if it's part of watermark_service
          for i in ${files_changed[@]}; do
              # Check if the file belongs to the watermark_service directory
              if [[ $i == watermark_service/* ]]; then
                  parent_folder=$(dirname $i)
                  parent_folders+=($parent_folder)
              fi
          done

          # If no changes in watermark_service, exit
          if [ ${#parent_folders[@]} -eq 0 ]; then
              echo "No changes detected in watermark_service"
              exit 0
          fi

          # Remove duplicates and sort the parent folders
          parent_folders=($(printf "%s\n" "${parent_folders[@]}" | sort -u))

          # Print the changed folders in watermark_service
          echo "Changed folders in watermark_service: ${parent_folders[@]}"

          # Format the final output for the matrix
          path=$(printf ",\"%s\"" "${parent_folders[@]}")
          path=${path:1}
          echo "Final path: ${path}"

          # Set output using environment files for GitHub Actions
          echo "matrix={\"path\": [ $path ] }" >> $GITHUB_ENV

      - name: Display changed folders
        run: |
          echo "The following folders in watermark_service have been changed: ${{ env.matrix }}"
