name: Deploy service

on:
  push:
    branches:
      - development
      - staging
      - main
    paths:
      - "text_embedding_service/**"
      - "watermark_service/**"
      - "image_embedding_service/**"
      - "thumbnail_service/**"
      - "brand_info_extraction_service/**"
      - "pinterest_api_service/**"
      - "openai_wrapper_service/**"
      - "image_generation_service/**"
      - "video_generation_service/**"

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  STAGE_TYPE: ${{ contains(github.ref, 'main') && 'prod' || contains(github.ref, 'staging') && 'stg' || 'dev' }}

jobs:
  update-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Change File Permissions for Scripts
        id: permission
        run: |
          chmod +x .github/scripts/check-files.sh
          chmod +x .github/scripts/extract-directory.sh

      - name: Get Changed Files
        id: getfile
        run: .github/scripts/check-files.sh

      - name: Debug Changed Files
        run: echo ${{ steps.getfile.outputs.files }}

      - name: Update Matrix
        id: set-matrix
        run: |
          matrix=$(.github/scripts/extract-directory.sh ${{ steps.getfile.outputs.files }})
          echo "::set-output name=matrix::$matrix"

  debug-matrix:
    needs: update-matrix
    runs-on: ubuntu-latest
    steps:
      - name: Debug the Matrix
        run: |-
          echo "Matrix Output: ${{ needs.update-matrix.outputs.matrix }}"
          echo "Parsed Matrix: ${{ fromJson(needs.update-matrix.outputs.matrix) }}"

  build_and_deploy:
    needs: update-matrix
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.update-matrix.outputs.matrix) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Update Environment Variables
        run: |-
          MATRIX_PATH="${{ matrix.path }}"
          echo "MATRIX_PATH=$MATRIX_PATH"  # Debugging the value of MATRIX_PATH
          if [ -z "$MATRIX_PATH" ]; then
            echo "Error: MATRIX_PATH is empty. Exiting."
            exit 1
          fi

          FOLDER=$(basename $MATRIX_PATH)
          SERVICE_NAME=platform-$FOLDER-$STAGE_TYPE
          SERVICE_NAME=${SERVICE_NAME//_/-}
          SERVICE_NAME=$(echo "$SERVICE_NAME" | tr '[:upper:]' '[:lower:]')
          IMAGE_URL=gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
          echo "SERVICE_NAME=$SERVICE_NAME" >> $GITHUB_ENV
          echo "IMAGE_URL=$IMAGE_URL" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build -t "${{ env.IMAGE_URL }}" ${{ matrix.path }}

      - name: Push Docker Image
        run: docker push ${{ env.IMAGE_URL }}

      - name: Deploy to Cloud Run
        run: |-
          # Define common deploy configuration
          deploy_common="--image ${{ env.IMAGE_URL }} \
                        --platform managed \
                        --region us-central1 \
                        --allow-unauthenticated \
                        --port 8000 \
                        --timeout 1200s \
                        --update-env-vars STAGE_TYPE=${{ env.STAGE_TYPE }}"

          # Deploy with different environment variables based on the service
          if [[ "${{ matrix.path }}" == *"brand_info_extraction_service"* || "${{ matrix.path }}" == *"openai_wrapper_service"* ]]; then
            echo "Deploying with OPENAI_API_KEY"
            gcloud run deploy ${{ env.SERVICE_NAME }} $deploy_common --update-env-vars OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          elif [[ "${{ matrix.path }}" == *"pinterest_api_service"* ]]; then
            echo "Deploying pinterest_api_service with PINTEREST_API_TOKEN"
            gcloud run deploy ${{ env.SERVICE_NAME }} $deploy_common --update-env-vars PINTEREST_API_TOKEN=${{ secrets.PINTEREST_API_TOKEN }}
          elif [[ "${{ matrix.path }}" == *"image_generation_service"* ]]; then
            echo "Deploying image_generation_service with REPLICATE_API_KEY, FALAI_API_KEY, and FASHN_API_KEY"
            gcloud run deploy ${{ env.SERVICE_NAME }} $deploy_common --update-env-vars REPLICATE_API_KEY=${{ secrets.REPLICATE_API_KEY }},FALAI_API_KEY=${{ secrets.FALAI_API_KEY }},FASHN_API_KEY=${{ secrets.FASHN_API_KEY }},OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }},FREEPIK_API_KEY=${{ secrets.FREEPIK_API_KEY }}
          elif [[ "${{ matrix.path }}" == *"video_generation_service"* ]]; then  # Add this condition
            echo "Deploying video_generation_service with REPLICATE_API_KEY"
            gcloud run deploy ${{ env.SERVICE_NAME }} $deploy_common --update-env-vars REPLICATE_API_KEY=${{ secrets.REPLICATE_API_KEY }}
          else
            echo "Deploying ${{ env.SERVICE_NAME }} without API keys"
            gcloud run deploy ${{ env.SERVICE_NAME }} $deploy_common
          fi
